SHOW DATABASES;
create DATABASE TEST11;
USE TEST11;

create table CUSTOMER(
CUSTOMER_id int NOT NULL auto_increment ,
CUSTOMER_name varchar(30) NOT NULL default 'unknown' ,
CUSTOMER_mailid varchar(30) unique NOT NULL ,
CUSTOMER_CITY varchar(30) NOT NULL ,
CUSTOMER_AMOUNT INT CHECK (CUSTOMER_AMOUNT > 10000) NOT NULL, 
primary key (CUSTOMER_id));
SELECT * FROM CUSTOMER;

INSERT INTO CUSTOMER(CUSTOMER_name,CUSTOMER_mailid,CUSTOMER_CITY,CUSTOMER_AMOUNT)VALUES
('SHIVAM', 'SHIVAM@GMAIL.COM', 'BARODA', 20000);
DROP TABLE CUSTOMER;
INSERT INTO CUSTOMER(CUSTOMER_name,CUSTOMER_mailid,CUSTOMER_CITY,CUSTOMER_AMOUNT)VALUES
('SHIVAM', 'SHIVAM@GMAIL.COM', 'BARODA', 20000),
('MAN', 'MAN@GMAIL.COM', 'PUNE', 30000),
('NAN', 'NAN@GMAIL.COM', 'AHMEDABAD', 40000),
('PARTH', 'PARTH@GMAIL.COM', 'BARODA', 60000);




