SHOW DATABASES;
CREATE DATABASE STUDENT1;
USE STUDENT1;

create table STUDENT1(
STUDENT_ID varchar(30),
STUDENT_NAME  varchar(30),
STUDENT_EMAIL varchar(30),
PERCENTAGE VARCHAR(30),
DEPARTMENT_ID VARCHAR(30)
);

INSERT INTO STUDENT1 VALUES
(1001,'AJAY','AJAY@XYZ.COM',85,1),
(1002,'BABLOO','BABLOO@XYZ.COM',67,2),
(1003,'CHHAVI','CHHAVI@XYZ.COM',89,3),
(1004,'DHEERAJ','DHEERAJ@XYZ.COM',75,4),
(1005,'EVINA','EVINA@XYZ.COM',91,1),
(1006,'KRISHNA','KRISHNA@XYZ.COM',99,5);


create table DEPARTMENT(
DEPARTMENT_ID varchar(30),
DEPARTMENT_NAME  varchar(30)
);
INSERT INTO DEPARTMENT VALUES
(1,'MATHEMATICS'),
(2,'PHYSICS'),
(3,'ENGLISH');


create table FACULTY(
DEPARTMENT_ID varchar(30),
FACULTY_NAME  varchar(30)
);

INSERT INTO faculty VALUES
(1,'PIYUSH'),
(2,'NAMITA'),
(3,'ASHNEER'),
(4,'GHAZAL'),
(5,'ANUPAM');

SELECT * FROM student1;
SELECT * FROM DEPARTMENT;
SELECT * FROM FACULTY;

#Q1 -- 1 & 3 TABLE
SELECT student1.DEPARTMENT_ID,student1.STUDENT_ID,student1.STUDENT_NAME,student1.STUDENT_EMAIL,student1.PERCENTAGE,
FACULTY.FACULTY_NAME FROM student1
INNER JOIN FACULTY
on student1.DEPARTMENT_ID = FACULTY.DEPARTMENT_ID;

#Q2 -- 1 & 3 TABLE
SELECT student1.DEPARTMENT_ID, student1.STUDENT_ID, student1.STUDENT_NAME,FACULTY.FACULTY_NAME from student1
INNER JOIN FACULTY
on  student1.DEPARTMENT_ID = FACULTY.DEPARTMENT_ID
WHERE FACULTY_NAME = 'PIYUSH' AND 'ASHNEER';

#Q3 -- THREE TABLE JOIN
SELECT student1.DEPARTMENT_ID, student1.STUDENT_ID, student1.STUDENT_NAME,student1.STUDENT_EMAIL,
DEPARTMENT.DEPARTMENT_NAME,FACULTY.FACULTY_NAME FROM STUDENT1
JOIN DEPARTMENT
ON student1.DEPARTMENT_ID = DEPARTMENT.DEPARTMENT_ID
JOIN FACULTY
ON FACULTY.DEPARTMENT_ID = DEPARTMENT.DEPARTMENT_ID;







