CREATE DATABASE LOOPPP ;
USE LOOPPP ; 

CREATE TABLE LOOP_TABLE(VAR INT) ;
## CARETE LOOP

DELIMITER $$
create procedure INSERT_DATA()
BEGIN 
SET @VAR = 10 ;
GENERATE_DATA : LOOP
INSERT INTO LOOP_TABLE VALUE (@VAR);
SET @VAR = @VAR + 1 ;
IF @VAR = 100 THEN 
      LEAVE GENERATE_DATA;
END IF ;
END LOOP GENERATE_DATA;
END $$
CALL INSERT_DATA();
SELECT * FROM  LOOP_TABLE ;


CREATE TABLE LOOP_TABLE1234(VAL INT,MULTI INT) ;
## CARETE LOOP

DELIMITER $$
create procedure INSERT_DATA1234()
BEGIN 
SET @VAR = 10 , @VAR1 = 10 ;
GENERATE_DATA : LOOP
INSERT INTO LOOP_TABLE1234 VALUE (@VAR,@VAR1);
SET @VAR = @VAR + 1 ;
IF @VAR = 50 THEN 
      LEAVE GENERATE_DATA;
END IF ;
SET @VAR1 = @VAR * 2;
IF @VAR1 = 50 THEN 
LEAVE GENERATE_DATA;
END IF;
END LOOP GENERATE_DATA;
END $$

CALL INSERT_DATA1234();
SELECT * FROM  LOOP_TABLE1234 ;






