USE CSVKIT;
delimiter //
CREATE FUNCTION ADD_TO_COLUMN(A INT)
RETURNS INT
deterministic
BEGIN 
     DECLARE B INT ;
     SET B = A + 20 ;
     RETURN B ;
END //

CREATE TABLE TEST100(
A INT(10),
B VARCHAR(10));
 
INSERT INTO TEST100 VALUE (10,'JALPA'),
(20,'BIJAL'),
(30,'RUTVIK');

SELECT * FROM TEST100;

SELECT A , ADD_TO_COLUMN(A) FROM TEST100;

delimiter $$
CREATE FUNCTION FINAL_PROFITS(PROFIT INT , DISCOUNT INT)
RETURNS INT
deterministic
BEGIN 
DECLARE FINAL_PROFIT INT ;
SET FINAL_PROFIT = PROFIT - DISCOUNT ;
RETURN FINAL_PROFIT;
END $$

SELECT PROFIT, DISCOUNT ,
FINAL_PROFITS(PROFIT,DISCOUNT) FROM SALES_DATA_FINAL1;

delimiter $$
CREATE FUNCTION FINAL_PROFITS_REAL(PROFIT DECIMAL (20,4),
DISCOUNT DECIMAL (10,4) , SALES DECIMAL (10,4))
RETURNS INT
deterministic
BEGIN 
DECLARE FINAL_PROFIT INT ;
SET FINAL_PROFIT = PROFIT - SALES * DISCOUNT ;
RETURN FINAL_PROFIT;
END $$

SELECT PROFIT, DISCOUNT ,SALES ,FINAL_PROFITS_REAL(PROFIT,DISCOUNT,SALES) FROM SALES_DATA_FINAL1;

ALTER TABLE sales_data_final1
ADD COLUMN FINAL_PROFIT INT;

UPDATE sales_data_final1 SET FINAL_PROFIT =FINAL_PROFITS_REAL(PROFIT,DISCOUNT,SALES) ;

SELECT * FROM sales_data_final1;

ALTER TABLE sales_data_final1
DROP COLUMN ORDER_DATE_NAME ;

ALTER TABLE sales_data_final1
ADD COLUMN FINAL_PROFIT_REAL INT;

UPDATE sales_data_final1 SET FINAL_PROFIT_REAL =FINAL_PROFITS_REAL(PROFIT,DISCOUNT,SALES) ;

DELIMITER &&
CREATE FUNCTION MARK_SALES2(SALES INT)
RETURNS VARCHAR(30)
DETERMINISTIC 
BEGIN
DECLARE FLAG_SALES VARCHAR(30);
IF SALES <= 100 THEN 
	SET FLAG_SALES = "SUPER AFFORDABLE PRODUCT" ;
ELSEIF SALES > 100 AND SALES < 300 THEN 
	SET FLAG_SALES = "AFFORADABLE" ;
ELSEIF SALES > 300 AND SALES < 600 THEN 
	SET FLAG_SALES = " MODERATE PRICE" ; 
ELSE
	SET FLAG_SALES = "EXPENSIVE" ;
END IF ;
RETURN FLAG_SALES;
END &&

ALTER TABLE sales_data_final1
ADD COLUMN FLAG_SALES1 ;

UPDATE sales_data_final1 SET FLAG_SALES = MARK_SALES2(SALES) ;

ALTER TABLE sales_data_final1
DROP COLUMN FLAG_SALES ;

ALTER TABLE sales_data_final1
ADD COLUMN FLAG_SALES1 VARCHAR(30) ;

UPDATE sales_data_final1 SET FLAG_SALES1 = MARK_SALES2(SALES) ;









